config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "places#index"
  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :user
    geocoded_by :address
    after_validation :geocode
  
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

    has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
  
    def index
        @places = Place.order("name").page(params[:page])
    end
  
    def new
      @place = Place.new
    end
  
    def create
        current_user.places.create(place_params)
        redirect_to root_path
    end

    def show
        @place = Place.find(params[:id])
      end
  
    private
  
    def place_params
      params.require(:place).permit(:name, :description, :address)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <%= link_to new_place_path, class: 'nav-link' do %>
          <i class="fa fa-plus-circle"></i>
          New Place
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/places/index.html.erb
<%= will_paginate @places %>

<% for place in @places %>
  <div class="booyah-box col-10 offset-1">
  <h1><%= place.name %></h1>
  <i><%= place.address %></i><br /><br />
  <p><%= place.description %></p><br />

  <% if place.user.present? %>
    <small><%= place.user.email %></small>
  <% end %>
</div>

  <hr />
<% end %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>
</div>